branches:
  except:
  - gh-pages
language:
- python
python:
- 3.3
- 3.4
- 3.5
- 3.6
before_install:
- >-
  openssl aes-256-cbc
  -K $encrypted_bfd322024369_key
  -iv $encrypted_bfd322024369_iv
  -in travis_secrets.tar.enc
  -out travis_secrets.tar
  -d
- tar xf travis_secrets.tar
- chmod 0600 travis_github_deploy_key
- cp travis_github_deploy_key ~/.ssh/id_rsa
script:
- python setup.py install
- make pre-commit
after_success:
# Only publish docs and coverage if it's a non-pull request on master with
# python 3.5.
- if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then echo "PR."; exit 0; fi
- if [[ "${TRAVIS_BRANCH}" != "master" ]]; then echo "Non-master."; exit 0; fi
- if [[ "${TRAVIS_PYTHON_VERSION}" != "3.5" ]]; then echo "Non 3.5."; exit 0; fi
- pip install python-coveralls
- coveralls
- make docs-publish
